export const preguntas = [
    { pregunta: "Bindi", respuesta: "Okra (quimbombó)" },
      { pregunta: "Jheenga (झींगा)", respuesta: "Camarón" },
      { pregunta: "Bengan (बैंगन)", respuesta: "Berenjena" },
      { pregunta: "Machi (मछली)", respuesta: "Pescado" },
      { pregunta: "Murgh (मुर्ग़)", respuesta: "Pollo" },
      { pregunta: "Tikka (टिक्का)", respuesta: "Marinado y asado" },
      { pregunta: "Masala (मसाला)", respuesta: "Mezcla de especias" },
      { pregunta: "Tandoori (तंदूरी)", respuesta: "Cocinado en horno de barro" },
      { pregunta: "Paneer (पनीर)", respuesta: "Queso fresco" },
      { pregunta: "Dal (दाल)", respuesta: "Lentejas" },
      { pregunta: "Aloo (आलू)", respuesta: "Papa" },
      { pregunta: "Matar (मटर)", respuesta: "Arvejas" },
      { pregunta: "Gobhi (गोभी)", respuesta: "Coliflor" },
      { pregunta: "Chana (चना)", respuesta: "Garbanzo" },
      { pregunta: "Kulfi (कुल्फी)", respuesta: "Helado indio" },
      { pregunta: "Gulab Jamun (गुलाब जामुन)", respuesta: "Dulce frito en jarabe de rosas" },
    { pregunta: "Bindi Oysters", respuesta: "Ostiones con tamarindo y okra" },
    { pregunta: "Chicken Lollipop 65", respuesta: "Trutros de pollo frito especiado" },
    { pregunta: "Empanadas de Butter chicken", respuesta: "Empanadas de pollo a la mantequilla" },
    { pregunta: "Goa Chilly Bengan", respuesta: "Berenjenas especiadas de Goa" },
    { pregunta: "Goa Chilly Jheenga", respuesta: "Camarones especiados de Goa" },
    { pregunta: "Jheenga Koliwada", respuesta: "Camarones fritos estilo Mumbai" },
    { pregunta: "Jheenga Til Tikka", respuesta: "Camarones apanados en sésamo" },
    { pregunta: "Johar E Motia", respuesta: "Champiñones en salsa blanca con castañas" },
    { pregunta: "Machi Koliwada", respuesta: "Pescado frito estilo Mumbai" },
    { pregunta: "Murgh Tikka", respuesta: "Pollo marinado al horno tandoor" },
    { pregunta: "Octopus Tikka Masala", respuesta: "Pulpo en salsa Tikka Masala" },
    { pregunta: "Pacora Mix", respuesta: "Frituras de queso y verduras" },
    { pregunta: "Paneer Tikka", respuesta: "Queso indio asado en tandoor" },
    { pregunta: "Samosas", respuesta: "Empanadillas de papa y especias" },
    { pregunta: "Tandoori Lamb Chop", respuesta: "Costilla de cordero al horno tandoor" },
    { pregunta: "Mathan Chop Kabbab", respuesta: "Costilla trozada de cordero" },
    { pregunta: "Murgh Reshmi Kabab", respuesta: "Pollo cremoso estilo Reshmi" },
    { pregunta: "Murgh Tandoori", respuesta: "Truto de pollo al horno tandoor" },
    { pregunta: "Murgh Tikka Pahadi", respuesta: "Pollo especiado con cilantro" },
    { pregunta: "Sheekh Kabbab de Cordero", respuesta: "Kebab de cordero" },
    { pregunta: "Tandoori Mix", respuesta: "Mezcla de kebabs variados" },
    { pregunta: "Achari Bengan", respuesta: "Berenjenas en encurtido de mango" },
    { pregunta: "Aloo Korma", respuesta: "Papas en salsa de castañas" },
    { pregunta: "Aloo Matar Aur Gobhi", respuesta: "Papas, arvejas y coliflor en curry" },
    { pregunta: "Angoori Khumb Aur Matar", respuesta: "Champiñones y arvejas en crema" },
    { pregunta: "Chana Pindi Batura", respuesta: "Garbanzos especiados con pan frito" },
    { pregunta: "Dal Makhani", respuesta: "Lentejas en mantequilla y especias" },
    { pregunta: "Dal Tadka", respuesta: "Lentejas rojas al curry" },
    { pregunta: "Kadai Paneer Tikka Masala", respuesta: "Queso paneer en salsa masala" },
    { pregunta: "Lahsuni Saag Paneer", respuesta: "Queso paneer en espinacas al ajo" },
    { pregunta: "Malai Kofta", respuesta: "Albóndigas de queso y frutos secos" },
    { pregunta: "Mattar Paneer", respuesta: "Queso paneer con arvejas" },
    { pregunta: "Veshnu Masala", respuesta: "Guiso mixto de verduras" },
    { pregunta: "Murgh Kali Mitch", respuesta: "Pollo en crema de pimienta" },
    { pregunta: "Murgh Nilgiri", respuesta: "Pollo cremoso con coco y menta" },
    { pregunta: "Murgh Tawa Masala", respuesta: "Pollo salteado en plancha" },
    { pregunta: "Achari Murgh Tikka Masala", respuesta: "Pollo ácido picante al tandoor" },
    { pregunta: "Murgh Mitha Suthra", respuesta: "Pollo dulce de almendra y coco" },
    { pregunta: "Karay Murgh Tikka Masala", respuesta: "Pollo especiado en tawa" },
    { pregunta: "Lasuni Saag Murgh", respuesta: "Pollo en espinacas al ajo" },
    { pregunta: "Butter Chicken", respuesta: "Pollo a la mantequilla" },
    { pregunta: "Murgh Curry", respuesta: "Pollo al curry tradicional" },
    { pregunta: "Murgh Adraki", respuesta: "Pollo al jengibre" },
    { pregunta: "Murgh Punjabi", respuesta: "Pollo estilo Punjabi especiado" },
    { pregunta: "Chapati Kekrey", respuesta: "Jaiba en salsa especiada" },
    { pregunta: "Goa Jheenga Curry", respuesta: "Camarones al curry de Goa" },
    { pregunta: "Goa Machi Curry", respuesta: "Pescado al curry de Goa" },
    { pregunta: "Jheenga Masaledar", respuesta: "Camarones muy especiados" },
    { pregunta: "Jheenga Mitha Sutra", respuesta: "Camarones en salsa dulce" },
    { pregunta: "Jheenga Punjabi", respuesta: "Camarones estilo Punjabi" },
    { pregunta: "Jheenga Tawa Masala", respuesta: "Camarones salteados en plancha" },
    { pregunta: "Balti Gosh", respuesta: "Cordero en curry de cebolla y tomate" },
    { pregunta: "Lamb Chop", respuesta: "Costilla francesa de cordero" },
    { pregunta: "Mathan Josh Curry", respuesta: "Cordero especiado al curry" },
    { pregunta: "Mathan Nilgiri", respuesta: "Cordero con coco y menta" },
    { pregunta: "AK-47", respuesta: "Pan indio con ají y queso" },
    { pregunta: "Cheese Naan", respuesta: "Pan naan con queso" },
    { pregunta: "Lasun Naan", respuesta: "Pan naan con ajo" },
    { pregunta: "Naan", respuesta: "Pan plano tradicional" },
    { pregunta: "Tandoori Kulcha", respuesta: "Pan relleno de cebolla y cilantro" },
    { pregunta: "Till Dania Naan", respuesta: "Pan naan con sésamo y cilantro" },
    { pregunta: "Arroz Basmati", respuesta: "Arroz aromático de grano largo" },
    { pregunta: "Kashmiri Pulao", respuesta: "Arroz basmati con frutas" },
    { pregunta: "Nimboo Baath", respuesta: "Arroz con limón y mostaza" },
    { pregunta: "Cheesecake de Pistacho", respuesta: "Pastel de queso con pistacho" },
    { pregunta: "Gulab Jamun", respuesta: "Dulce frito en jarabe de rosas" },
    { pregunta: "Kulfi", respuesta: "Helado tradicional indio" },
    { pregunta: "Volcán de Chocolate", respuesta: "Bizcocho de chocolate fundido" }
  ];

